// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/edit-application/page.tsx
import Link from "next/link";
import { ChevronLeft } from "lucide-react";

import { Breadcrumbs } from "@/components/Breadcrumbs";
import { EditApplicationForm } from "./(components)/edit-application-form";
import { getApplicationByIdService } from "@/services/dashboard/get-application-by-id";

type Props = {
  params: Promise<{
    organizationId: string;
    applicationId: string;
  }>;
};

export default async function EditApplicationPage({ params }: Props) {
  const { applicationId, organizationId } = await params;

  const [application, err] = await getApplicationByIdService(
    { applicationId, organizationId },
    { accessToken: "" }
  );

  if (err) {
    return <div>Failed to fetch application</div>;
  }

  return (
    <>
      <Breadcrumbs
        items={[
          { name: "Dashboard", path: `/dashboard/${organizationId}` },
          {
            name: "Applications",
            path: `/dashboard/${organizationId}/application`,
          },
          {
            name: application?.name || "-",
            path: `/dashboard/${organizationId}/application/${applicationId}`,
          },
          {
            name: "Edit Application",
            path: `/dashboard/${organizationId}/application/${applicationId}/edit-application`,
          },
        ]}
      />

      <main className="flex flex-col p-4">
        <Link
          href={`/dashboard/${organizationId}/application/${applicationId}`}
          className="text-md mb-4 flex items-center gap-2 text-gray-600 dark:text-gray-300 hover:dark:text-gray-500 hover:text-gray-800 hover:underline"
        >
          <ChevronLeft size={24} />
          Go back to application details
        </Link>

        <h2 className="text-3xl font-bold tracking-tight">Edit Application</h2>

        <span className="mt-3 text-sm tracking-tight text-gray-600 dark:text-gray-300">
          Here you can edit the application. Fill in the form below and click
          the &quot;Apply Changes&quot; button to edit the application.
        </span>

        <EditApplicationForm application={application} />
      </main>
    </>
  );
}

// app/src/routes/dashboard/application/[applicationId]/edit-application/+page.svelte
<script lang="ts">
	import ChevronLeft from "lucide-svelte/icons/chevron-left";
    
    import Breadcrumbs from "../../../(components)/breadcrumbs.svelte";
	import type { PageData } from "./$types";
	import EditApplicationForm from "./(components)/edit-application-form.svelte";
	import { page } from "$app/state";

    let { data }: { data: PageData } = $props();

	$inspect(data);
</script>

<Breadcrumbs
	items={[
		{ name: 'Dashboard', path: '/dashboard' },
		{ name: 'Applications', path: '/dashboard/application' },
		{ name: 'Edit Application', path: '/dashboard/application/1/edit-application' }
	]}
/>

<main class="flex flex-col p-4">
	<a href="/dashboard/application/" class="hover:underline flex items-center text-md gap-2 text-gray-600 hover:text-gray-800 mb-4">
		<ChevronLeft size={24} />
		Go back to applications details
	</a>

    <h2 class="text-3xl font-bold tracking-tight">
        Edit Application
    </h2>

	<span class="mt-3 text-sm tracking-tight text-gray-600">
        Here you can edit the application. Fill in the form below and click the "Apply Changes" button to edit the application.
	</span>

    <EditApplicationForm data={data} />
</main>
