// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/roles/delete-role-dialog.tsx
"use client";

import { useState } from "react";

import { Button, buttonVariants } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ApplicationRole } from ".";

type Props = {
  isOpened: boolean;
  onOpenChange: (value: boolean) => void;
  role: ApplicationRole | null;
};

export function DeleteRoleDialog({ isOpened, onOpenChange }: Props) {
  const [isLoading, setIsLoading] = useState(false);

  function handler() {
    setIsLoading(true);

    // Logic here
    setIsLoading(false);

    onOpenChange(false);
  }

  return (
    <Dialog open={isOpened} onOpenChange={(value) => onOpenChange(value)}>
      <DialogContent className="sm:max-w-[450px]">
        <DialogHeader>
          <DialogTitle>Delete User</DialogTitle>

          <DialogDescription>
            On deleting this user, it will be permanently removed from the
            application. Are you sure?
          </DialogDescription>
        </DialogHeader>

        <DialogFooter>
          <DialogClose className={buttonVariants({ variant: "outline" })}>
            Cancel
          </DialogClose>

          <Button type="submit" onClick={handler} variant="destructive">
            {isLoading ? "Deleting..." : "Delete"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// app/src/routes/dashboard/application/[applicationId]/(components)/roles/delete-role-dialog.svelte
<script lang="ts">
	
	import * as Dialog from '$lib/components/ui/dialog';
	import { buttonVariants } from '$lib/components/ui/button';
	import Button from '$lib/components/ui/button/button.svelte';
	import type { IApplication } from "$lib/services/use-application-by-id-query";
	import type { Writable } from "svelte/store";

	let isLoading = $state(false);

	type Props = {
		role: IApplication["roles"]["data"][number] | null;
		isDeleteModalOpened: Writable<boolean>;
	}

	let { role, isDeleteModalOpened }: Props = $props();

	function handler() {
		isLoading = true;

		// Logic here
		isLoading = false;
	}
</script>

<Dialog.Root open={$isDeleteModalOpened} onOpenChange={(value) => isDeleteModalOpened.set(value)}>
	<Dialog.Content class="sm:max-w-[450px]">
		<Dialog.Header>
			<Dialog.Title>Delete Application Role</Dialog.Title>
			<Dialog.Description>v 
				On deleting this role ({role?.name}), it will be permanently removed from the server. Are you sure?
			</Dialog.Description>
		</Dialog.Header>


		<Dialog.Footer>
			<Dialog.Close class={buttonVariants({ variant: 'outline' })}>
				Cancel
			</Dialog.Close>

			<Button type="submit" onclick={handler}>
                {#if isLoading}
                    Deleting...
                {:else}
                    Delete
                {/if}
            </Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
