// next-app/src/components/Breadcrumbs.tsx
import { Fragment } from "react";

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { SidebarTrigger } from "@/components/ui/sidebar";

type Props = {
  items: {
    name: string;
    path: string;
  }[];
};

export function Breadcrumbs({ items }: Props) {
  return (
    <div className="flex gap-4 items-center">
      <SidebarTrigger />

      <Breadcrumb>
        <BreadcrumbList>
          {items.map((item, index) => (
            <Fragment key={index}>
              <BreadcrumbItem>
                <BreadcrumbLink href={item.path}>{item.name}</BreadcrumbLink>
              </BreadcrumbItem>

              {index !== items.length - 1 && <BreadcrumbSeparator />}
            </Fragment>
          ))}
        </BreadcrumbList>
      </Breadcrumb>
    </div>
  );
}

// app/src/routes/dashboard/(components)/breadcrumbs.svelte
<script lang="ts">
	  import * as Breadcrumb from "$lib/components/ui/breadcrumb/index.js";
      import * as Sidebar from "$lib/components/ui/sidebar/";

      let { items }: { items: { name: string; path: string }[] } = $props();
</script>

<div class="flex gap-4 items-center">
    <Sidebar.Trigger />

    <Breadcrumb.Root>
        <Breadcrumb.List>

            {#each items as item, i (item.name) }
                <Breadcrumb.Item>
                    <Breadcrumb.Link href={item.path}>{item.name}</Breadcrumb.Link>
                </Breadcrumb.Item>
        
                {#if i !== items.length -1}
                    <Breadcrumb.Separator />
                {/if}
            {/each}
        </Breadcrumb.List>
    </Breadcrumb.Root>
</div>
