// app/src/routes/dashboard/application/[applicationId]/user/[userId]/(components)/application-roles-section.svelte
<script lang="ts">
	import * as Tooltip from '$lib/components/ui/tooltip';
	import Label from '$lib/components/ui/label/label.svelte';
	import Checkbox from '$lib/components/ui/checkbox/checkbox.svelte';

	type Props = { isEditEnabled: boolean };

	let { isEditEnabled }: Props = $props();
</script>

<div class="flex flex-col gap-1">
	<span class="text-sm font-medium"> Application Roles </span>

	<span class="text-muted-foreground my-2 text-sm">
		Choose the roles that will be assigned to this user.
	</span>

	<div class="flex items-center space-x-2">
		<Checkbox id="asd1" disabled={!isEditEnabled} />

		<Tooltip.Provider>
			<Tooltip.Root>
				<Tooltip.Trigger>
					<Label
						for="asd1"
						data-isEditEnabled={isEditEnabled}
						class="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 data-[isEditEnabled=false]:font-normal"
					>
						User
					</Label>
				</Tooltip.Trigger>

				<Tooltip.Content>User Description</Tooltip.Content>
			</Tooltip.Root>
		</Tooltip.Provider>
	</div>

	<div class="flex items-center space-x-2">
		<Checkbox id="asd2" disabled={!isEditEnabled} />

		<Tooltip.Provider>
			<Tooltip.Root>
				<Tooltip.Trigger>
					<Label
						for="asd2"
						data-isEditEnabled={isEditEnabled}
						class="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 data-[isEditEnabled=false]:font-normal"
					>
						Admin
					</Label>
				</Tooltip.Trigger>

				<Tooltip.Content>Admin Description</Tooltip.Content>
			</Tooltip.Root>
		</Tooltip.Provider>
	</div>
</div>

// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/user/create-user/(components)/application-roles-section.tsx
"use client";

import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

import { FormType } from "./user-detail-form";
import { IApplication } from "@/services/dashboard/get-application-by-id";

type Props = {
  form: FormType;
  roles: IApplication["roles"]["data"];
};

export function ApplicationRolesSection({ form, roles }: Props) {
  return (
    <div className="flex flex-col gap-1">
      <span className="text-sm font-medium"> Application Roles </span>

      <span className="text-muted-foreground my-2 text-sm">
        Choose the roles that will be assigned to this user.
      </span>

      {roles.map((role) => (
        <div className="flex items-center space-x-2" key={role.id}>
          <Checkbox
            id={role.id}
            checked={form.getValues("roles").includes(role.id)}
            onCheckedChange={(checked) => {
              const currentRoles = form.getValues("roles");

              if (checked) {
                form.setValue("roles", [...currentRoles, role.id]);
              } else {
                form.setValue(
                  "roles",
                  currentRoles.filter((r) => r !== role.id)
                );
              }

              console.log(form.getValues("roles"), { checked });
            }}
          />

          <Tooltip>
            <TooltipTrigger>
              <Label
                htmlFor={role.id}
                className="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                {role.name}
              </Label>
            </TooltipTrigger>

            <TooltipContent>{role.description}</TooltipContent>
          </Tooltip>
        </div>
      ))}
    </div>
  );
}
