// app/src/routes/dashboard/(components)/dashboard-side-bar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';

	import Plus from 'lucide-svelte/icons/plus';
	import Logout from 'lucide-svelte/icons/log-out';
	import LayoutPanelLeft from 'lucide-svelte/icons/layout-panel-left';

	import * as Avatar from '$lib/components/ui/avatar';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';

	import { useApplicationsQuery } from '$lib/services/use-applications-query';
	import OrganizationsInput from './organizations-input.svelte';

	const items = [
		{
			title: 'Applications',
			url: '/dashboard/application',
			icon: LayoutPanelLeft
		}
	];

	const path = $derived(page.url.pathname);

	let applications = useApplicationsQuery({ accessToken: '' });
</script>

<Sidebar.Root variant="sidebar">
	<Sidebar.Header>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<div>
					<OrganizationsInput />
				</div>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>

	<Sidebar.Content>
		<Sidebar.Group>
			<Sidebar.GroupLabel>General</Sidebar.GroupLabel>

			<Sidebar.GroupContent>
				<Sidebar.Menu>
					{#each items as item (item.title)}
						<Sidebar.MenuItem>
							<Sidebar.MenuButton isActive={item.url === path}>
								{#snippet child({ props })}
									<a href={item.url} {...props}>
										<item.icon />
										<span>{item.title}</span>
									</a>
								{/snippet}
							</Sidebar.MenuButton>
						</Sidebar.MenuItem>
					{/each}
				</Sidebar.Menu>
			</Sidebar.GroupContent>
		</Sidebar.Group>

		<Sidebar.Group>
			<Sidebar.GroupLabel>Applications</Sidebar.GroupLabel>
			<Sidebar.GroupAction
				title="Add Project"
				onclick={() => goto('/dashboard/application/create-application')}
			>
				<Plus /> <span class="sr-only">Add Project</span>
			</Sidebar.GroupAction>

			<Sidebar.GroupContent>
				<Sidebar.Menu>
					{#each $applications?.data || [] as application (application?.id)}
						<Sidebar.MenuItem>
							<Sidebar.MenuButton>
								{#snippet child({ props })}
									<a href={`/dashboard/application/${application.id}`} {...props}>
										<span>{application.name}</span>
									</a>
								{/snippet}
							</Sidebar.MenuButton>
						</Sidebar.MenuItem>
					{/each}
				</Sidebar.Menu>
			</Sidebar.GroupContent>
		</Sidebar.Group>
	</Sidebar.Content>

	<Sidebar.Footer>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton>
					<Logout />
					Logout
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>

		<Sidebar.Separator />

		<div class="flex gap-2">
			<Avatar.Root>
				<Avatar.Image src="https://github.com/shadcn.png" alt="@shadcn" />
				<Avatar.Fallback>CN</Avatar.Fallback>
			</Avatar.Root>

			<div class="flex flex-col">
				<span class="text-sm font-semibold">John Doe</span>
				<span class="text-sm">Johndoe@email.com</span>
			</div>
		</div>
	</Sidebar.Footer>
</Sidebar.Root>

// next-app/src/components/DashboardSidebar/index.tsx
"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { LayoutPanelLeft, LogOut, Plus } from "lucide-react";

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from "@/components/ui/sidebar";

import { OrganizationList } from "./OrganizationList";
import { useApplicationsSWR } from "@/services/dashboard/use-applications-swr";
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar";

import { ThemeToggle } from "../ui/theme-togle";

export function DashboardSidebar() {
  const organizationId = useParams().organizationId as string;
  const { data } = useApplicationsSWR({ organizationId }, { accessToken: "" });

  const items = [
    {
      title: "Applications",
      url: `/dashboard/${organizationId}/application`,
      icon: LayoutPanelLeft,
    },
  ];

  return (
    <Sidebar collapsible="icon">
      <SidebarHeader>
        <SidebarMenu>
          <OrganizationList />
        </SidebarMenu>
      </SidebarHeader>

      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel>General</SidebarGroupLabel>

          <SidebarGroupContent>
            <SidebarMenu>
              {items.map((item, index) => (
                <SidebarMenuItem key={index}>
                  <SidebarMenuButton asChild tooltip={item.title}>
                    <Link href={item.url}>
                      <item.icon />
                      <span>{item.title}</span>
                    </Link>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              ))}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        <SidebarGroup className="group-data-[collapsible=icon]:hidden">
          <SidebarGroupLabel>Applications</SidebarGroupLabel>

          <SidebarGroupAction title="Add Application" onClick={() => {}}>
            <Plus /> <span className="sr-only">Add Application</span>
          </SidebarGroupAction>

          <SidebarGroupContent>
            <SidebarMenu>
              {data?.map((application) => (
                <SidebarMenuItem key={application.id}>
                  <SidebarMenuButton asChild>
                    <Link
                      href={`/dashboard/${organizationId}/application/${application.id}`}
                    >
                      {application.name}
                    </Link>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              ))}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>

      <SidebarFooter>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton>
              <LogOut />
              Logout
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>

        <ThemeToggle />

        <div className="flex gap-2">
          <Avatar>
            <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>

          <div className="flex flex-col">
            <span className="text-sm font-semibold">John Doe</span>
            <span className="text-sm">Johndoe@email.com</span>
          </div>
        </div>
      </SidebarFooter>
    </Sidebar>
  );
}
