// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/providers/ProviderCard.tsx
"use client";

import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Switch } from "@/components/ui/switch";
import { useState } from "react";

type Props = {
  title: string;
  description: string;
  isEnabled: boolean;
  clientId: string;
  clientSecret: string;
};

export function ProviderCard({
  clientId,
  clientSecret,
  description,
  isEnabled,
  title,
}: Props) {
  const [draftClientId, setDraftClientId] = useState(clientId);
  const [draftClientSecret, setDraftClientSecret] = useState(clientSecret);
  const [draftIsEnabled, setDraftIsEnabled] = useState(isEnabled);

  return (
    <Sheet>
      <SheetTrigger>
        <Card className="transition-all hover:scale-[1.01] hover:cursor-pointer hover:shadow-lg">
          <CardHeader>
            <CardTitle className="flex flex-wrap justify-between gap-4">
              {title}
            </CardTitle>

            <CardDescription className="text-left">
              {description}
            </CardDescription>
          </CardHeader>

          <CardContent className="flex gap-1">
            <Badge variant="outline" className="w-fit">
              {draftClientId && draftClientSecret
                ? "Configured"
                : "Not configured"}
            </Badge>

            <Badge
              variant={draftIsEnabled ? "default" : "secondary"}
              className="w-fit"
            >
              {draftIsEnabled ? "Enabled" : "Disabled"}
            </Badge>
          </CardContent>
        </Card>
      </SheetTrigger>

      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>Configure Provider</SheetTitle>
          <SheetDescription>
            Make changes to your Google authentication provider configuration.
            Then click &quot;Save changes&quot; to apply them.
          </SheetDescription>
        </SheetHeader>

        <div className="my-4 flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <Label htmlFor="client-id">Client ID</Label>
            <Input
              id="client-id"
              value={draftClientId}
              type="text"
              placeholder="Type the client ID"
              className="col-span-3"
              onChange={(e) => setDraftClientId(e.target.value)}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="client-secret">Client Secret</Label>
            <Input
              id="client-secret"
              type="password"
              placeholder="Type the client secret"
              value={draftClientSecret}
              className="col-span-3"
              onChange={(e) => setDraftClientSecret(e.target.value)}
            />
          </div>

          <div className="flex items-center space-x-2">
            <Switch
              id="provider-enabled"
              checked={draftIsEnabled}
              onChange={() => setDraftIsEnabled(!draftIsEnabled)}
            />

            <Label htmlFor="provider-enabled">
              {draftIsEnabled ? "Enabled" : "Disabled"}
            </Label>
          </div>
        </div>

        <SheetFooter>
          <SheetClose className={buttonVariants({ variant: "default" })}>
            Save changes
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}

// app/src/routes/dashboard/application/[applicationId]/(components)/providers/(components)/provider-card.svelte
<script lang="ts">
	import * as Sheet from '$lib/components/ui/sheet/';
	import * as Card from '$lib/components/ui/card';
	import { Switch } from '$lib/components/ui/switch';

	import Badge from '$lib/components/ui/badge/badge.svelte';
	import Label from '$lib/components/ui/label/label.svelte';
	import Input from '$lib/components/ui/input/input.svelte';
	import { buttonVariants } from '$lib/components/ui/button';

	type Props = {
		title: string;
		description: string;
		isEnabled: boolean;
		clientId: string;
		clientSecret: string;
	};

	let { title, description, clientId, clientSecret, isEnabled }: Props = $props();

	let draftTitle = $derived(title);
	let draftDescription = $derived(description);
	let draftClientId = $derived(clientId);
	let draftClientSecret = $derived(clientSecret);
	let draftIsEnabled = $derived(isEnabled);
</script>

<Sheet.Root>
	<Sheet.Trigger>
		<Card.Root class="transition-all hover:scale-[1.01] hover:cursor-pointer hover:shadow-lg">
			<Card.Header>
				<Card.Title class="flex flex-wrap justify-between gap-4">{draftTitle}</Card.Title>

				<Card.Description class="text-left">
					{draftDescription}
				</Card.Description>
			</Card.Header>

			<Card.Content class="flex gap-1">
				<Badge variant="outline" class="w-fit">
					{draftClientId && draftClientSecret ? 'Configured' : 'Not configured'}
				</Badge>

				<Badge variant={draftIsEnabled ? 'default' : 'secondary'} class="w-fit">
					{draftIsEnabled ? 'Enabled' : 'Disabled'}
				</Badge>
			</Card.Content>
		</Card.Root>
	</Sheet.Trigger>

	<Sheet.Content side="right">
		<Sheet.Header>
			<Sheet.Title>Configure Provider</Sheet.Title>
			<Sheet.Description>
				Make changes to your Google authentication provider configuration. Then click "Save changes"
				to apply them.
			</Sheet.Description>
		</Sheet.Header>

		<div class="my-4 flex flex-col gap-4">
			<div class="flex flex-col gap-2">
				<Label for="client-id">Client ID</Label>
				<Input
					id="client-id"
					value={draftClientId}
					type="text"
					placeholder="Type the client ID"
					class="col-span-3"
				/>
			</div>

			<div class="flex flex-col gap-2">
				<Label for="client-secret">Client Secret</Label>
				<Input
					id="client-secret"
					type="password"
					placeholder="Type the client secret"
					value={draftClientSecret}
					class="col-span-3"
				/>
			</div>

			<div class="flex items-center space-x-2">
				<Switch id="provider-enabled" checked={draftIsEnabled} />
				<Label for="provider-enabled">{draftIsEnabled ? 'Enabled' : 'Disabled'}</Label>
			</div>
		</div>

		<Sheet.Footer>
			<Sheet.Close class={buttonVariants({ variant: 'default' })}>Save changes</Sheet.Close>
		</Sheet.Footer>
	</Sheet.Content>
</Sheet.Root>
