// next-app/src/app/auth/[applicationId]/sign-in/(components)/auth-form.tsx
"use client";

import { z } from "zod";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { useParams } from "next/navigation";

import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

import { formSchema } from "./auth-schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { useState } from "react";

export function AuthForm() {
  const applicationId = useParams().applicationId;

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

  const [isLoading] = useState(false);

  function onSubmit(values: z.infer<typeof formSchema>) {
    // Do something with the form values.
    // ✅ This will be type-safe and validated.
    console.log(values);
  }

  return (
    <div className="grid gap-4">
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-3">
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>E-mail</FormLabel>
                <FormControl>
                  <Input
                    placeholder="example@email.com"
                    autoComplete="email"
                    type="email"
                    {...field}
                  />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Password</FormLabel>
                <FormControl>
                  <Input
                    placeholder="********"
                    autoComplete="new-password"
                    type="password"
                    {...field}
                  />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <div className="flex items-center justify-between gap-2">
            <Link
              href={`/auth/${applicationId}/forgot-password`}
              className="text-md mb-2 text-center hover:underline"
            >
              Forgot password
            </Link>

            <Link
              href={`/auth/${applicationId}/sign-up`}
              className="font-semibold text-md text-center hover:underline"
            >
              Create an account
            </Link>
          </div>

          <Button type="submit" disabled={isLoading} className="w-full">
            Sign In with Email
          </Button>
        </form>
      </Form>

      <div className="relative">
        <div className="absolute inset-0 flex items-center">
          <span className="w-full border-t"></span>
        </div>

        <div className="relative flex justify-center text-xs uppercase">
          <span className="bg-background text-muted-foreground px-2">
            {" "}
            Or continue with{" "}
          </span>
        </div>
      </div>

      <div className="flex flex-col gap-1">
        <Button variant="outline" type="button" disabled={isLoading}>
          GitHub
        </Button>
      </div>
    </div>
  );
}

// app/src/routes/auth/[applicationId]/sign-in/(components)/auth-form.svelte
<script lang="ts">
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';

	import * as Form from '$lib/components/ui/form';
	import Button from '$lib/components/ui/button/button.svelte';
	import Input from '$lib/components/ui/input/input.svelte';

	import { cn } from '$lib/utils.js';
	import { formSchema, type FormSchema } from '../schema';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import type { PageData } from '../$types';

	let {
		data,
		class: className
	}: {
		data: PageData;
		class?: string | null;
	} = $props();

	let isLoading = $state(false);
	let applicationId = page.params.applicationId;

	const form = superForm(data.form, { validators: zodClient(formSchema) });
	const { form: formData, enhance } = form;

	async function onSubmit() {
		isLoading = true;

		goto(`/auth/${applicationId}/one-time-password`);

		setTimeout(() => {
			isLoading = false;
		}, 3000);
	}
</script>

<div class={cn('grid gap-4', className)}>
	<form on:submit|preventDefault={onSubmit}>
		<div class="grid gap-2">
			<Form.Field {form} name="email">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>E-mail</Form.Label>
						<Input
							{...props}
							bind:value={$formData.email}
							placeholder="example@email.com"
							autocomplete="email"
						/>
					{/snippet}
				</Form.Control>
				<Form.Description />
				<Form.FieldErrors />
			</Form.Field>

			<Form.Field {form} name="password">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>Password</Form.Label>
						<Input
							{...props}
							bind:value={$formData.password}
							placeholder="********"
							autocomplete="new-password"
						/>
					{/snippet}
				</Form.Control>
				<Form.Description />
				<Form.FieldErrors />
			</Form.Field>

			<div class="flex items-center justify-between gap-2">
				<a
					href={`/auth/${applicationId}/forgot-password`}
					class="text-md mb-2 text-center hover:underline">Forgot password</a
				>

				{#if data.applicationData?.canSelfRegister}
					<a href={`/auth/${applicationId}/sign-up`} class="font-semibold text-md text-center hover:underline">
						Create an account
					</a>
				{/if}
			</div>

			<Button type="submit" disabled={isLoading}>Sign In with Email</Button>
		</div>
	</form>

	<div class="relative">
		<div class="absolute inset-0 flex items-center">
			<span class="w-full border-t"></span>
		</div>
		<div class="relative flex justify-center text-xs uppercase">
			<span class="bg-background text-muted-foreground px-2"> Or continue with </span>
		</div>
	</div>

	<div class="flex flex-col gap-1">
		{#each data.applicationData?.oauthProviders || [] as provider}
			<Button variant="outline" type="button" disabled={isLoading}>
				{provider.name}
			</Button>
		{/each}
	</div>
</div>
