// app/src/routes/auth/[applicationId]/change-password/(components)/auth-form.svelte
<script lang="ts">
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';

	import * as Form from '$lib/components/ui/form';
	import Button from '$lib/components/ui/button/button.svelte';
	import Input from '$lib/components/ui/input/input.svelte';

	import { cn } from '$lib/utils.js';
	import { formSchema, type FormSchema } from '../schema';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';

	let {
		data,
		class: className
	}: {
		data: { form: SuperValidated<Infer<FormSchema>> };
		class?: string | null;
	} = $props();

	let applicationId = page.params.applicationId;
	let isLoading = $state(false);

	const form = superForm(data.form, { validators: zodClient(formSchema) });
	const { form: formData, enhance } = form;

	async function onSubmit() {
		isLoading = true;

		goto(`/auth/${applicationId}/one-time-password`);

		setTimeout(() => {
			isLoading = false;
		}, 3000);
	}
</script>

<div class={cn('grid gap-4', className)}>
	<form on:submit|preventDefault={onSubmit}>
		<div class="grid gap-2">
			<Form.Field {form} name="password">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>New Password</Form.Label>
						<Input
							{...props}
							bind:value={$formData.password}
							placeholder="********"
							autocomplete="new-password"
						/>
					{/snippet}
				</Form.Control>
				<Form.Description />
				<Form.FieldErrors />
			</Form.Field>

            <Form.Field {form} name="confirmPassword">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>Confirm Your Password</Form.Label>
						<Input
							{...props}
							bind:value={$formData.confirmPassword}
							placeholder="********"
							autocomplete="new-password"
						/>
					{/snippet}
				</Form.Control>
				<Form.Description />
				<Form.FieldErrors />
			</Form.Field>

			<Button type="submit" disabled={isLoading}>Save New Password</Button>
		</div>
	</form>
</div>

// next-app/src/app/auth/[applicationId]/change-password/(components)/auth-form.tsx
"use client";

import { z } from "zod";
import { toast } from "sonner";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { useParams, useSearchParams } from "next/navigation";

import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

import { formSchema } from "./auth-schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { resetPasswordApi } from "@/services/auth/reset-password";

export function AuthForm() {
  const applicationId = useParams().applicationId as string;
  const searchParams = useSearchParams();

  const passwordResetToken = searchParams.get("token");
  const passwordResetId = searchParams.get("id");

  const [isLoading, setIsLoading] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      password: "",
      confirmPassword: "",
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    if (!applicationId) {
      console.error("Application ID is required");
      toast.error("Application ID is required");
      return;
    }

    if (!passwordResetToken) {
      console.error("Password reset token is required");
      toast.error("Password reset token is required");
      return;
    }

    if (!passwordResetId) {
      console.error("Password reset ID is required");
      toast.error("Password reset ID is required");
      return;
    }

    setIsLoading(true);

    const [err] = await resetPasswordApi({
      applicationId,
      newPassword: values.password,
      passwordResetToken,
      passwordResetId,
    });

    if (err) {
      console.error(err);
      toast.error(err.response?.data?.message || err.message);
      setIsLoading(false);
      return;
    }

    setIsLoading(false);

    toast.success("Password reset successfully");
  }

  return (
    <div className="grid gap-4">
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-3">
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Password</FormLabel>
                <FormControl>
                  <Input
                    placeholder="********"
                    autoComplete="new-password"
                    type="password"
                    {...field}
                  />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="confirmPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Confirm Password</FormLabel>
                <FormControl>
                  <Input placeholder="********" type="password" {...field} />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button type="submit" disabled={isLoading} className="w-full">
            Save Password
          </Button>
        </form>
      </Form>
    </div>
  );
}
