// app/src/routes/dashboard/application/[applicationId]/(components)/users/delete-user-dialog.svelte
<script lang="ts">
	import Trash from 'lucide-svelte/icons/trash-2';

	import * as Dialog from '$lib/components/ui/dialog';
	import { buttonVariants } from '$lib/components/ui/button';
	import Button from '$lib/components/ui/button/button.svelte';
	import type { IApplication } from '$lib/services/use-application-by-id-query';
	import type { Writable } from 'svelte/store';

	type Props = {
		user: IApplication["users"]["data"][number] | null;
		isDeleteModalOpened: Writable<boolean>;
	}

	let { user, isDeleteModalOpened }: Props = $props();

	let isLoading = $state(false);

	function handler() {
		isLoading = true;

		// Logic here
		isLoading = false;
		
		isDeleteModalOpened.set(false);
	}
</script>

<Dialog.Root open={$isDeleteModalOpened} onOpenChange={(value) => isDeleteModalOpened.set(value)}>
	<Dialog.Content class="sm:max-w-[450px]">
		<Dialog.Header>
			<Dialog.Title>Delete User</Dialog.Title>
			<Dialog.Description>
				On deleting this user, it will be permanently removed from the application. Are you sure?
			</Dialog.Description>
		</Dialog.Header>

		<Dialog.Footer>
			<Dialog.Close class={buttonVariants({ variant: 'outline' })}>Cancel</Dialog.Close>

			<Button type="submit" onclick={handler} variant="destructive">
				{#if isLoading}
					Deleting...
				{:else}
					Delete
				{/if}
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>

// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/users/delete-user-dialog.tsx
"use client";

import { useState } from "react";

import { Button, buttonVariants } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ApplicationUser } from "./columns";

type Props = {
  isOpened: boolean;
  onOpenChange: (value: boolean) => void;
  user: ApplicationUser | null;
};

export function DeleteUserDialog({ isOpened, onOpenChange }: Props) {
  const [isLoading, setIsLoading] = useState(false);

  function handler() {
    setIsLoading(true);

    // Logic here
    setIsLoading(false);

    onOpenChange(false);
  }

  return (
    <Dialog open={isOpened} onOpenChange={(value) => onOpenChange(value)}>
      <DialogContent className="sm:max-w-[450px]">
        <DialogHeader>
          <DialogTitle>Delete User</DialogTitle>

          <DialogDescription>
            On deleting this user, it will be permanently removed from the
            application. Are you sure?
          </DialogDescription>
        </DialogHeader>

        <DialogFooter>
          <DialogClose className={buttonVariants({ variant: "outline" })}>
            Cancel
          </DialogClose>

          <Button type="submit" onClick={handler} variant="destructive">
            {isLoading ? "Deleting..." : "Delete"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
