// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/providers/index.tsx
import { IApplication } from "@/services/dashboard/get-application-by-id";
import { ProviderCard } from "./ProviderCard";

type Props = {
  application: IApplication | null;
};

export function Providers({ application }: Props) {
  return (
    <div className="grid grid-cols-3 gap-3">
      {application?.oauthProviders.map((provider) => (
        <ProviderCard
          key={provider.id}
          title={provider.name}
          description={provider.description}
          isEnabled={provider.isEnabled}
          clientId={provider.clientId}
          clientSecret={provider.clientSecret}
        />
      ))}
    </div>
  );
}

// app/src/routes/dashboard/application/[applicationId]/(components)/providers/providers.svelte
<script lang="ts">
	import type { IApplication } from '$lib/services/use-application-by-id-query';
	import ProviderCard from './(components)/provider-card.svelte';

	type Props = { application?: IApplication | null };

	let { application }: Props = $props();
</script>

<div class="grid grid-cols-3 gap-3">
	{#each application?.oauthProviders || [] as provider (provider.id)}
		<ProviderCard
			title={provider.name}
			description={provider.description}
			isEnabled={provider.isEnabled}
			clientId={provider.clientId}
			clientSecret={provider.clientSecret}
		/>
	{/each}
</div>
