// app/src/routes/dashboard/application/[applicationId]/(components)/overview/delete-secret-dialog.svelte
<script lang="ts">
	import Trash from 'lucide-svelte/icons/trash-2';

	import * as Dialog from '$lib/components/ui/dialog';
	import { buttonVariants } from '$lib/components/ui/button';
	import Button from '$lib/components/ui/button/button.svelte';
	import type { IApplication } from '$lib/services/use-application-by-id-query';
	import { deleteApplicationSecretApi } from '$lib/services/delete-application-secret';
	import { organizationStore } from '$lib/stores/organization';
	import { toast } from 'svelte-sonner';

	let isLoading = $state(false);

	type Props = {
		secret: IApplication['secrets'][number];
		applicationId?: IApplication['id'];
	};

	let { secret, applicationId }: Props = $props();

	async function handler() {
		if (!applicationId) {
			toast.error('Application ID is missing');
			return;
		}

		isLoading = true;

		const [err] = await deleteApplicationSecretApi(
			{
				applicationId: applicationId,
				secretId: secret.id,
				organizationId: $organizationStore?.id
			},
			{ accessToken: '' }
		);

		if (err) {
			toast.error('Failed to delete secret');
			console.error(err);
			isLoading = false;
			return;
		}

		// Logic here
		isLoading = false;
	}
</script>

<Dialog.Root>
	<Dialog.Trigger class={buttonVariants({ variant: 'outline' })}>
		<Trash />
	</Dialog.Trigger>

	<Dialog.Content class="sm:max-w-[450px]">
		<Dialog.Header>
			<Dialog.Title>Delete Application Secret</Dialog.Title>
			<Dialog.Description>
				On deleting this secret ({secret.name}), it will be permanently removed from the server. Are
				you sure?
			</Dialog.Description>
		</Dialog.Header>

		<Dialog.Footer>
			<Dialog.Close class={buttonVariants({ variant: 'outline' })}>Cancel</Dialog.Close>

			<Button type="submit" onclick={handler}>
				{#if isLoading}
					Deleting...
				{:else}
					Delete
				{/if}
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>

// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/overview/delete-secret-dialog.tsx
"use client";

import { toast } from "sonner";
import { useState } from "react";
import { Trash } from "lucide-react";
import { useParams } from "next/navigation";

import { Button, buttonVariants } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

import { deleteApplicationSecretApi } from "@/services/dashboard/delete-application-secret";
import { IApplication } from "@/services/dashboard/get-application-by-id";

type Props = {
  secret: IApplication["secrets"][number];
};

export function DeleteSecretDialog({ secret }: Props) {
  const [isLoading, setIsLoading] = useState(false);
  const params = useParams();

  const { applicationId, organizationId } = params as {
    applicationId: string;
    organizationId: string;
  };

  async function handler() {
    if (!applicationId) {
      toast.error("Application ID is missing");
      return;
    }

    setIsLoading(true);

    const [err] = await deleteApplicationSecretApi(
      {
        applicationId: applicationId,
        secretId: secret.id,
        organizationId,
      },
      { accessToken: "" }
    );

    if (err) {
      toast.error("Failed to delete secret");
      console.error(err);
      setIsLoading(false);
      return;
    }

    // Logic here
    setIsLoading(false);
  }

  return (
    <Dialog>
      <DialogTrigger className={buttonVariants({ variant: "outline" })}>
        <Trash />
      </DialogTrigger>

      <DialogContent className="sm:max-w-[450px]">
        <DialogHeader>
          <DialogTitle>Delete Application Secret</DialogTitle>
          <DialogDescription>
            On deleting this secret ({secret.name}), it will be permanently
            removed from the server. Are you sure?
          </DialogDescription>
        </DialogHeader>

        <DialogFooter>
          <DialogClose className={buttonVariants({ variant: "outline" })}>
            Cancel
          </DialogClose>

          <Button type="submit" onClick={handler}>
            {isLoading ? "Deleting..." : "Delete"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
