// app/src/routes/dashboard/application/[applicationId]/(components)/overview/overview.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card';
	import * as Tooltip from '$lib/components/ui/tooltip';
	import Badge from '$lib/components/ui/badge/badge.svelte';

	import NewSecretDialog from './new-secret-dialog.svelte';
	import DeleteSecretDialog from './delete-secret-dialog.svelte';
	import type { IApplication } from '$lib/services/use-application-by-id-query';
	import { formatDate } from '$lib/utils';

	type Props = { application?: IApplication | null };

	let { application }: Props = $props();
</script>

<section class="flex w-full flex-col gap-y-4">
	<Card.Root class="w-full transition-all">
		<Card.Header>
			<Card.Title>Info</Card.Title>
			<Card.Description>Information about the application.</Card.Description>
		</Card.Header>

		<Card.Content class="flex flex-wrap gap-x-8 gap-y-4">
			<div class="flex flex-col">
				<span class="text-md font-semibold">Application ID</span>
				<span class="text-sm">{application?.id}</span>
			</div>

			<div class="flex flex-col">
				<span class="text-md font-semibold">Status</span>
				{#if !application?.deactivatedAt}
					<Badge variant="default">Active</Badge>
				{:else}
					<Badge variant="destructive" class="flex gap-1">
						Deactivated at{' '}
						<span class="text-white">{formatDate(application?.deactivatedAt)}</span>
					</Badge>
				{/if}
			</div>

			<div class="flex flex-col">
				<span class="text-md font-semibold">Multi Factor Auth</span>
				{#if application?.multiFactorAuthEnabled}
					<Badge variant="outline" class="w-fit">Yes</Badge>
				{:else}
					<Badge variant="outline" class="w-fit">No</Badge>
				{/if}
			</div>
		</Card.Content>
	</Card.Root>

	<Card.Root class="w-full transition-all">
		<Card.Header>
			<Card.Title class="flex flex-wrap justify-between gap-4">
				Secrets

				<NewSecretDialog />
			</Card.Title>
			<Card.Description>
				Secrets are used to authenticate your application with the server. Keep them safe.
			</Card.Description>
		</Card.Header>

		<Card.Content class="flex flex-col gap-y-4">
			{#each application?.secrets || [] as secret (secret.id)}
				<div class="flex items-center gap-4">
					<div class="space-y-1">
						<p class="text-sm font-medium leading-none">{secret.name}</p>
						<p class="text-muted-foreground">{secret.value}</p>
					</div>

					<div class="ml-auto text-sm">
						Expiração: <span class="text-md font-medium"
							>{secret.expirationDate ? formatDate(secret.expirationDate) : 'Lifetime'}</span
						>
					</div>

					<Tooltip.Provider>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<DeleteSecretDialog {secret} applicationId={application?.id} />
							</Tooltip.Trigger>

							<Tooltip.Content>
								<p>Delete secret</p>
							</Tooltip.Content>
						</Tooltip.Root>
					</Tooltip.Provider>
				</div>
			{/each}
		</Card.Content>
	</Card.Root>
</section>

// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/overview/index.tsx
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

// import { formatDate } from "@/lib/utils";
import { NewSecretDialog } from "./new-secret-dialog";
import { DeleteSecretDialog } from "./delete-secret-dialog";

import { IApplication } from "@/services/dashboard/get-application-by-id";
import { formatDate } from "@/lib/utils";

type Props = {
  application: IApplication | null;
};

export function Overview({ application }: Props) {
  return (
    <section className="flex w-full flex-col gap-y-4">
      <Card className="w-full transition-all">
        <CardHeader>
          <CardTitle>Info</CardTitle>
          <CardDescription>Information about the application.</CardDescription>
        </CardHeader>

        <CardContent className="flex flex-wrap gap-x-8 gap-y-4">
          <div className="flex flex-col">
            <span className="text-md font-semibold">Application ID</span>
            <span className="text-sm">{application?.id}</span>
          </div>

          <div className="flex flex-col">
            <span className="text-md font-semibold">Status</span>
            {!application?.deactivatedAt ? (
              <Badge variant="default">Active</Badge>
            ) : (
              <Badge variant="destructive" className="flex gap-1">
                Deactivated at{" "}
                <span className="text-white">
                  {application?.deactivatedAt &&
                    formatDate(application.deactivatedAt)}
                </span>
              </Badge>
            )}
          </div>

          <div className="flex flex-col">
            <span className="text-md font-semibold">Multi Factor Auth</span>
            {application?.multiFactorAuthEnabled ? (
              <Badge variant="outline" className="w-fit">
                Yes
              </Badge>
            ) : (
              <Badge variant="outline" className="w-fit">
                No
              </Badge>
            )}
          </div>
        </CardContent>
      </Card>

      <Card className="w-full transition-all">
        <CardHeader>
          <CardTitle className="flex flex-wrap justify-between gap-4">
            Secrets
            <NewSecretDialog />
          </CardTitle>

          <CardDescription>
            Secrets are used to authenticate your application with the server.
            Keep them safe.
          </CardDescription>
        </CardHeader>

        <CardContent className="flex flex-col gap-y-4">
          {application?.secrets.map((secret) => (
            <div className="flex items-center gap-4" key={secret.id}>
              <div className="space-y-1">
                <p className="text-sm font-medium leading-none">
                  {secret.name}
                </p>
                <p className="text-muted-foreground">{secret.value}</p>
              </div>

              <div className="ml-auto text-sm">
                Expiração:{" "}
                <span className="text-md font-medium">
                  {secret?.expirationDate
                    ? formatDate(new Date(secret.expirationDate))
                    : "Lifetime"}
                </span>
              </div>

              <Tooltip>
                <TooltipTrigger asChild>
                  <DeleteSecretDialog secret={secret} />
                </TooltipTrigger>

                <TooltipContent>
                  <p>Delete secret</p>
                </TooltipContent>
              </Tooltip>
            </div>
          ))}
        </CardContent>
      </Card>
    </section>
  );
}
