// next-app/src/app/auth/[applicationId]/confirm-email/page.tsx
import Link from "next/link";
import { Fragment } from "react";
import { ArrowLeftIcon } from "lucide-react";

import { AuthForm } from "./(components)/AuthForm";

type Props = {
  params: Promise<{ applicationId: string }>;
};

export default async function SignInPage({ params }: Props) {
  const { applicationId } = await params;

  return (
    <Fragment>
      <Link
        href={`/auth/${applicationId}/sign-in`}
        className="text-primary flex items-center gap-3 hover:underline absolute top-4 left-4"
      >
        <div className="flex items-center justify-center rounded-md bg-secondary text-primary p-2 hover:brightness-90 transition-all">
          <ArrowLeftIcon />
        </div>
        Back to sign in
      </Link>

      <div className="flex flex-col space-y-2 text-center">
        <h1 className="text-2xl font-semibold tracking-tight">
          Confirm E-mail
        </h1>
        <p className="text-muted-foreground text-sm">
          We sent a confirmation code to your e-mail. Enter the code below to
          confirm your e-mail
        </p>
      </div>

      <AuthForm />
    </Fragment>
  );
}

// app/src/routes/auth/confirm-email/+page.svelte
<script lang="ts">
	import type { PageData } from '../one-time-password/$types';
	import AuthForm from './(components)/auth-form.svelte';

	let { data }: { data: PageData } = $props();
</script>

<div class="flex flex-col space-y-2 text-center">
	<h1 class="text-2xl font-semibold tracking-tight">Confirm E-mail</h1>
	<p class="text-muted-foreground text-sm">We sent a confirmation code to your e-mail. Enter the code below to confirm your e-mail</p>
</div>

<AuthForm {data} />
