// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/(components)/delete-application-dialog.tsx
"use client";

import { useState } from "react";
import { Trash } from "lucide-react";

import { Button, buttonVariants } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

export function DeleteApplicationDialog() {
  const [isLoading, setIsLoading] = useState(false);

  async function handler() {
    setIsLoading(true);

    // Logic here
    setIsLoading(false);
  }

  return (
    <Dialog>
      <DialogTrigger className={buttonVariants({ variant: "destructive" })}>
        <Trash />
      </DialogTrigger>

      <DialogContent className="sm:max-w-[450px]">
        <DialogHeader>
          <DialogTitle>Delete Application</DialogTitle>
          <DialogDescription>
            On deleting this application, it will be permanently removed from
            the organization. Are you sure?
          </DialogDescription>
        </DialogHeader>

        <DialogFooter>
          <DialogClose className={buttonVariants({ variant: "outline" })}>
            Cancel
          </DialogClose>

          <Button type="submit" onClick={handler} variant="destructive">
            {isLoading ? "Deleting..." : "Delete"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// app/src/routes/dashboard/application/[applicationId]/(components)/delete-application-dialog.svelte
<script lang="ts">
	import Trash from 'lucide-svelte/icons/trash-2';

	import * as Dialog from '$lib/components/ui/dialog';
	import { buttonVariants } from '$lib/components/ui/button';
	import Button from '$lib/components/ui/button/button.svelte';

	let isLoading = $state(false);

	function handler() {
		isLoading = true;

		// Logic here
		isLoading = false;
	}
</script>

<Dialog.Root>
	<Dialog.Trigger class={buttonVariants({ variant: 'destructive' })}>
		<Trash />
	</Dialog.Trigger>

	<Dialog.Content class="sm:max-w-[450px]">
		<Dialog.Header>
			<Dialog.Title>Delete Application</Dialog.Title>
			<Dialog.Description>
				On deleting this application, it will be permanently removed from the organization. Are you
				sure?
			</Dialog.Description>
		</Dialog.Header>

		<Dialog.Footer>
			<Dialog.Close class={buttonVariants({ variant: 'outline' })}>Cancel</Dialog.Close>

			<Button type="submit" onclick={handler} variant="destructive">
				{#if isLoading}
					Deleting...
				{:else}
					Delete
				{/if}
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
