// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/edit-application/(components)/edit-application-form.tsx
"use client";

import { z } from "zod";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { MultiSelectInput } from "@/components/ui/multi-select-input";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

import { StrongPasswordDialog } from "../../../create-application/(components)/strong-password-dialog";

import { formSchema } from "../schema";
import { IApplication } from "@/services/dashboard/get-application-by-id";

type Props = {
  application: IApplication | null;
};

export function EditApplicationForm({ application }: Props) {
  const [isLoading, setIsLoading] = useState(false);
  const [isStrongPasswordModalOpened, setIsStrongPasswordModalOpened] =
    useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: application?.name ?? "",
      passwordHashSecret: application?.passwordHashingSecret ?? "",
      description: application?.description ?? "",
      badges: application?.badges ?? [],
      hasMfaAuthApp: application?.mfaEmailEnabled ?? false,
      hasMfaEmail: application?.mfaAuthAppEnabled ?? false,
    },
  });

  function onSubmit() {
    setIsLoading(true);

    console.log(form.getValues());

    setTimeout(() => {
      setIsLoading(false);
    }, 2000);
  }

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="mt-4 max-w-[700px]"
      >
        <div className="grid gap-2">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="flex gap-1">
                  Name
                  <span className="text-red-500">*</span>
                </FormLabel>

                <FormControl>
                  <Input
                    placeholder="Type the application name"
                    autoComplete="name"
                    type="text"
                    {...field}
                  />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage></FormMessage>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="flex gap-1">Description</FormLabel>

                <FormControl>
                  <Textarea
                    placeholder="Type the application description"
                    autoComplete="description"
                    {...field}
                  />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage></FormMessage>
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="badges"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Badges</FormLabel>
                <FormControl>
                  <MultiSelectInput
                    items={field.value}
                    onChange={(values: string[]) =>
                      form.setValue("badges", values)
                    }
                  />
                </FormControl>

                <FormDescription></FormDescription>
                <FormMessage></FormMessage>
              </FormItem>
            )}
          />

          <Separator className="my-2" />

          <FormField
            control={form.control}
            name="passwordHashSecret"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="flex gap-1">
                  Password Hash Secret
                  <span className="text-red-500">*</span>
                </FormLabel>
                <FormControl>
                  <Input
                    placeholder="Type the application password hash"
                    autoComplete="name"
                    type="password"
                    {...field}
                  />
                </FormControl>

                <StrongPasswordDialog
                  setPassword={(value) =>
                    form.setValue("passwordHashSecret", value)
                  }
                  isModalOpened={isStrongPasswordModalOpened}
                  onOpenChange={setIsStrongPasswordModalOpened}
                />

                <FormDescription>
                  This is the secret that will be used to hash all the passwords
                  from users that are registered to this application.
                </FormDescription>
                <FormMessage></FormMessage>
              </FormItem>
            )}
          />

          <Separator className="my-2" />

          <div className="flex flex-col gap-3">
            <span className="text-sm font-medium">
              Multi Factor Authentication
            </span>

            <span className="text-muted-foreground text-sm">
              Choose the methods that will be used for multi factor
              authentication.
            </span>

            <FormField
              control={form.control}
              name="hasMfaEmail"
              render={({ field }) => (
                <FormItem className="flex items-center space-x-2">
                  <FormControl>
                    <Checkbox
                      checked={!!field.value}
                      onCheckedChange={field.onChange}
                      aria-labelledby="terms-label"
                    />
                  </FormControl>

                  <FormLabel className="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                    E-mail
                  </FormLabel>

                  <FormDescription></FormDescription>
                  <FormMessage></FormMessage>
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="hasMfaAuthApp"
              render={({ field }) => (
                <FormItem className="flex items-center space-x-2">
                  <FormControl>
                    <Checkbox
                      checked={!!field.value}
                      onCheckedChange={field.onChange}
                      aria-labelledby="terms-label"
                    />
                  </FormControl>

                  <FormLabel className="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                    Authenticator App (Microsoft, Google, etc)
                  </FormLabel>

                  <FormDescription></FormDescription>
                  <FormMessage></FormMessage>
                </FormItem>
              )}
            />
          </div>

          <Button type="submit" disabled={isLoading} className="ml-auto w-fit">
            {isLoading ? "Saving changes..." : "Update Application"}
          </Button>
        </div>
      </form>
    </Form>
  );
}

// app/src/routes/dashboard/application/[applicationId]/edit-application/(components)/edit-application-form.svelte
<script lang="ts">
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';
	
	import * as Form from '$lib/components/ui/form';
	import { Checkbox } from "$lib/components/ui/checkbox";
	import { Textarea } from '$lib/components/ui/textarea';
	import Input from '$lib/components/ui/input/input.svelte';
	import Label from '$lib/components/ui/label/label.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import Separator from '$lib/components/ui/separator/separator.svelte';
	import MultiSelectInput from '$lib/components/ui/multi-select-input/multi-select-input.svelte';

	import { formSchema, type FormSchema } from '../schema';
	import StrongPasswordModal from './strong-password-modal.svelte';
	import { toast } from 'svelte-sonner';

	type Props = { data: { form: SuperValidated<Infer<FormSchema>> } } 
	let { data }: Props = $props();

	let isLoading = $state(false);

	const form = superForm(data.form, { validators: zodClient(formSchema) });
	const { form: formData } = form;

	async function onSubmit(
		e: SubmitEvent & {
			currentTarget: EventTarget & HTMLFormElement;
		}
	) {
		e.preventDefault();
		isLoading = true;

		setTimeout(() => {
			isLoading = false
			toast.success('Application created successfully!')
		}, 3000);
	}

	let badges: string[] = $state([]);
	let passwordHashSecret = $state('');

	$effect(() => {
		$formData.passwordHashSecret = passwordHashSecret;
	});
</script>

<form onsubmit={onSubmit} class="mt-4 max-w-[600px]">
	<div class="grid gap-2">
		<Form.Field {form} name="name">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>
						Name
						<span class="text-red-500">*</span>
					</Form.Label>
					<Input
						{...props}
						bind:value={$formData.name}
						placeholder="Type the application name"
						autocomplete="name"
					/>
				{/snippet}
			</Form.Control>
			<Form.Description></Form.Description>
			<Form.FieldErrors></Form.FieldErrors>
		</Form.Field>

		<Form.Field {form} name="Description">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Description</Form.Label>
					<Textarea
						{...props}
						bind:value={$formData.Description}
						placeholder="Type the application description"
					/>
				{/snippet}
			</Form.Control>
			<Form.Description></Form.Description>
			<Form.FieldErrors></Form.FieldErrors>
		</Form.Field>

		<Form.Field {form} name="badges">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Badges</Form.Label>
					<MultiSelectInput items={badges} />
				{/snippet}
			</Form.Control>

			<Form.Description>
				This is used to categorize the application. You can add multiple badges to the application.
			</Form.Description>
			<Form.FieldErrors></Form.FieldErrors>
		</Form.Field>

		<Separator />

		<Form.Field {form} name="passwordHashSecret">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>
						Password Hash Secret
						<span class="text-red-500">*</span>
					</Form.Label>

					<Input
						{...props}
						bind:value={passwordHashSecret}
						placeholder="Type the password hash secret"
						type="text"
					/>
				{/snippet}
			</Form.Control>

			<StrongPasswordModal setPassword={(value) => (passwordHashSecret = value)} />

			<Form.Description>
				This is the secret that will be used to hash all the passwords from users that are
				registered to this application.
			</Form.Description>
			<Form.FieldErrors></Form.FieldErrors>
		</Form.Field>

		<Separator />

		<div class="flex flex-col gap-3">
			<span class="font-medium text-sm">
				Multi Factor Authentication
			</span>

			<span class="text-sm text-muted-foreground">
				Choose the methods that will be used for multi factor authentication.
			</span>

			<div class="flex items-center space-x-2">
				<Checkbox id="e-mail-mfa" checked={false} aria-labelledby="terms-label" />
	
				<Label
				  id="e-mail-mfa-label"
				  for="e-mail-mfa"
				  class="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
				>
				  E-mail
				</Label>
			</div>
	
			<div class="flex items-center space-x-2">
				<Checkbox id="auth-app-mfa" checked={false} aria-labelledby="terms-label" />
	
				<Label
				  id="auth-app-mfa-label"
				  for="auth-app-mfa"
				  class="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
				>
				  Authenticator App (Microsoft, Google, etc)
				</Label>
			</div>
		</div>

		<Button type="submit" disabled={isLoading} class="ml-auto w-fit">
			{#if isLoading}
				Creating Application...
			{:else}
				Create Application
			{/if}
		</Button>
	</div>
</form>
