// app/src/routes/dashboard/application/[applicationId]/user/create-user/(components)/application-roles-section.svelte
<script lang="ts">
	import * as Tooltip from '$lib/components/ui/tooltip';
	import Label from '$lib/components/ui/label/label.svelte';
	import Checkbox from '$lib/components/ui/checkbox/checkbox.svelte';

	type Props = {  };

	let {  }: Props = $props();
</script>

<div class="flex flex-col gap-1">
	<span class="text-sm font-medium"> Application Roles </span>

	<span class="text-muted-foreground my-2 text-sm">
		Choose the roles that will be assigned to this user.
	</span>

	<div class="flex items-center space-x-2">
		<Checkbox id="asd1" />

		<Tooltip.Provider>
			<Tooltip.Root>
				<Tooltip.Trigger>
					<Label
						for="asd1"
						class="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
					>
						User
					</Label>
				</Tooltip.Trigger>

				<Tooltip.Content>User Description</Tooltip.Content>
			</Tooltip.Root>
		</Tooltip.Provider>
	</div>

	<div class="flex items-center space-x-2">
		<Checkbox id="asd2" />

		<Tooltip.Provider>
			<Tooltip.Root>
				<Tooltip.Trigger>
					<Label
						for="asd2"
						class="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
					>
						Admin
					</Label>
				</Tooltip.Trigger>

				<Tooltip.Content>Admin Description</Tooltip.Content>
			</Tooltip.Root>
		</Tooltip.Provider>
	</div>
</div>

// next-app/src/app/dashboard/[organizationId]/application/[applicationId]/user/[userId]/(components)/application-roles-section.tsx
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

type Props = {
  isEditEnabled: boolean;
};

export function ApplicationRolesSection({ isEditEnabled }: Props) {
  console.log(isEditEnabled);

  return (
    <div className="flex flex-col gap-1">
      <span className="text-sm font-medium"> Application Roles </span>

      <span className="text-muted-foreground my-2 text-sm">
        Choose the roles that will be assigned to this user.
      </span>

      <div className="flex items-center space-x-2">
        <Checkbox id="asd1" />

        <Tooltip>
          <TooltipTrigger>
            <Label
              htmlFor="asd1"
              className="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              User
            </Label>
          </TooltipTrigger>

          <TooltipContent>User Description</TooltipContent>
        </Tooltip>
      </div>

      <div className="flex items-center space-x-2">
        <Checkbox id="asd2" />

        <Tooltip>
          <TooltipTrigger>
            <Label
              htmlFor="asd2"
              className="text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Admin
            </Label>
          </TooltipTrigger>

          <TooltipContent>Admin Description</TooltipContent>
        </Tooltip>
      </div>
    </div>
  );
}
